package com.richardsand.novelkms.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.math.BigInteger;
import java.util.List;
import java.util.UUID;

import javax.imageio.ImageIO;

import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTSectPr;

import com.richardsand.novelkms.NovelKmsTestBase;
import com.richardsand.novelkms.dao.PageLayoutDao;
import com.richardsand.novelkms.dao.PartDao;
import com.richardsand.novelkms.dao.TemplateDao;
import com.richardsand.novelkms.model.PageLayout;
import com.richardsand.novelkms.model.Part;
import com.richardsand.novelkms.model.Project;
import com.richardsand.novelkms.model.book.Book;
import com.richardsand.novelkms.model.chapter.Chapter;

/**
 * Covers {@link ExportService} (DOCX) across all four export scopes: content
 * fidelity (headings, scene breaks, images, cover-template tokens) and
 * page-layout dimension mapping.
 *
 * <p>
 * Tests re-open the generated bytes with POI and inspect paragraphs/sections
 * directly, the same way a human reviewer would open the file in Word.
 */
class ExportServiceTest extends NovelKmsTestBase {

    private PartDao       partDao;
    private PageLayoutDao pageLayoutDao;
    private ExportService service;

    private Project project;
    private Book    book;

    @BeforeEach
    void setUp() throws Exception {
        truncateAll();
        partDao = new PartDao(ds);
        pageLayoutDao = new PageLayoutDao(ds);
        service = new ExportService(bookDao, partDao, chapterDao, sceneDao, projectDao, templateDao, pageLayoutDao);

        project = projectDao.create("Test Project", null);
        book = bookDao.create(project.getId(), "The Long Way Home", null, "Long Way", null);
    }

    // -------------------------------------------------------------------------
    // Scene scope
    // -------------------------------------------------------------------------

    @Test
    void exportSceneReturnsRawContentWithNoHeading() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "Chapter One", null, null);
        var scene = sceneDao.create(chapter.getId(), "Opening", null);
        sceneDao.saveContent(scene.getId(), "<p>The rain had not stopped for three days.</p>", 8);

        ExportService.ExportMeta meta = service.exportScene(scene.getId());

        assertTrue(meta.filename().endsWith(".docx"));
        List<String> paragraphs = paragraphTexts(meta.bytes());
        assertTrue(paragraphs.stream().anyMatch(p -> p.contains("The rain had not stopped for three days.")));
        assertFalse(paragraphs.stream().anyMatch(p -> p.contains("Chapter One")));
    }

    @Test
    void exportSceneThrowsForUnknownId() {
        assertThrows(IllegalArgumentException.class, () -> service.exportScene(UUID.randomUUID()));
    }

    // -------------------------------------------------------------------------
    // Chapter scope
    // -------------------------------------------------------------------------

    @Test
    void exportChapterIncludesChapterTitleHeading() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "The Beginning", "A Prologue", null);
        var scene = sceneDao.create(chapter.getId(), "Scene 1", null);
        sceneDao.saveContent(scene.getId(), "<p>It started, as these things do, with a letter.</p>", 9);

        ExportService.ExportMeta meta = service.exportChapter(chapter.getId());

        List<String> paragraphs = paragraphTexts(meta.bytes());
        assertTrue(paragraphs.stream().anyMatch(p -> p.equals("The Beginning")));
        assertTrue(paragraphs.stream().anyMatch(p -> p.equals("A Prologue")));
        assertTrue(paragraphs.stream().anyMatch(p -> p.contains("It started, as these things do")));
    }

    @Test
    void exportChapterRendersSceneBreakBetweenMultipleScenes() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "Two Scenes", null, null);
        var sceneA = sceneDao.create(chapter.getId(), "A", null);
        sceneDao.saveContent(sceneA.getId(), "<p>First scene content.</p>", 3);
        var sceneB = sceneDao.create(chapter.getId(), "B", null);
        sceneDao.saveContent(sceneB.getId(), "<p>Second scene content.</p>", 3);

        ExportService.ExportMeta meta = service.exportChapter(chapter.getId());

        List<String> paragraphs = paragraphTexts(meta.bytes());
        long sceneBreakCount = paragraphs.stream().filter(p -> p.equals("* * *")).count();
        assertEquals(1, sceneBreakCount);

        int firstIdx = indexOfContaining(paragraphs, "First scene content");
        int breakIdx = paragraphs.indexOf("* * *");
        int secondIdx = indexOfContaining(paragraphs, "Second scene content");
        assertTrue(firstIdx < breakIdx && breakIdx < secondIdx);
    }

    @Test
    void exportChapterConvertsInlineHorizontalRuleToSceneBreak() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "One Scene, Inline Break", null, null);
        var scene = sceneDao.create(chapter.getId(), "Only", null);
        sceneDao.saveContent(scene.getId(),
                "<p>Before the break.</p><hr><p>After the break.</p>", 6);

        ExportService.ExportMeta meta = service.exportChapter(chapter.getId());

        List<String> paragraphs = paragraphTexts(meta.bytes());
        assertTrue(paragraphs.contains("* * *"));
        int beforeIdx = indexOfContaining(paragraphs, "Before the break");
        int breakIdx = paragraphs.indexOf("* * *");
        int afterIdx = indexOfContaining(paragraphs, "After the break");
        assertTrue(beforeIdx < breakIdx && breakIdx < afterIdx);
    }

    @Test
    void exportChapterThrowsForUnknownId() {
        assertThrows(IllegalArgumentException.class, () -> service.exportChapter(UUID.randomUUID()));
    }

    // -------------------------------------------------------------------------
    // Part scope
    // -------------------------------------------------------------------------

    @Test
    void exportPartIncludesPartHeadingAndAllItsChapters() throws Exception {
        Part part = partDao.create(book.getId(), "Origins", "How it all began", null);
        Chapter ch1 = chapterDao.create(book.getId(), part.getId(), "First Light", null, null);
        sceneDao.saveContent(sceneDao.create(ch1.getId(), "s", null).getId(), "<p>Dawn broke.</p>", 2);
        Chapter ch2 = chapterDao.create(book.getId(), part.getId(), "Second Light", null, null);
        sceneDao.saveContent(sceneDao.create(ch2.getId(), "s", null).getId(), "<p>Noon came.</p>", 2);

        ExportService.ExportMeta meta = service.exportPart(part.getId());

        List<String> paragraphs = paragraphTexts(meta.bytes());
        assertTrue(paragraphs.stream().anyMatch(p -> p.equals("Origins")));
        assertTrue(paragraphs.stream().anyMatch(p -> p.equals("How it all began")));
        assertTrue(paragraphs.stream().anyMatch(p -> p.equals("First Light")));
        assertTrue(paragraphs.stream().anyMatch(p -> p.equals("Second Light")));
    }

    @Test
    void exportPartFallsBackToRomanNumeralWhenTitleBlank() throws Exception {
        Part part = partDao.create(book.getId(), "", null, null);

        ExportService.ExportMeta meta = service.exportPart(part.getId());

        List<String> paragraphs = paragraphTexts(meta.bytes());
        assertTrue(paragraphs.stream().anyMatch(p -> p.startsWith("Part ")));
    }

    // -------------------------------------------------------------------------
    // Book scope
    // -------------------------------------------------------------------------

    @Test
    void exportBookOrdersPartChaptersBeforeDirectChapters() throws Exception {
        Part part = partDao.create(book.getId(), "Part One", null, null);
        Chapter inPart = chapterDao.create(book.getId(), part.getId(), "In The Part", null, null);
        sceneDao.saveContent(sceneDao.create(inPart.getId(), "s", null).getId(), "<p>Inside the part.</p>", 3);
        Chapter direct = chapterDao.create(book.getId(), null, "Direct Chapter", null, null);
        sceneDao.saveContent(sceneDao.create(direct.getId(), "s", null).getId(), "<p>Outside any part.</p>", 3);

        ExportService.ExportMeta meta = service.exportBook(book.getId());

        List<String> paragraphs = paragraphTexts(meta.bytes());
        int partIdx = paragraphs.indexOf("Part One");
        int inPartIdx = paragraphs.indexOf("In The Part");
        int directIdx = paragraphs.indexOf("Direct Chapter");
        assertTrue(partIdx < inPartIdx);
        assertTrue(inPartIdx < directIdx);
    }

    @Test
    void exportBookEmbedsCoverImageWhenPresent() throws Exception {
        bookDao.setCoverImage(book.getId(), tinyPng(), "image/png");
        Chapter chapter = chapterDao.create(book.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Content.</p>", 1);

        ExportService.ExportMeta meta = service.exportBook(book.getId());

        try (XWPFDocument doc = new XWPFDocument(new ByteArrayInputStream(meta.bytes()))) {
            assertFalse(doc.getAllPictures().isEmpty());
        }
    }

    @Test
    void exportBookResolvesCoverTemplateTokens() throws Exception {
        Project updatedProject = Project.builder()
                .id(project.getId())
                .title(project.getTitle())
                .authorFirstName("Jane")
                .authorLastName("Doe")
                .copyright("\u00a9 2026 Jane Doe")
                .build();
        projectDao.update(updatedProject);

        templateDao.upsertBookOverride(book.getId(), TemplateDao.TYPE_COVER, """
                <p data-style="cover_title" style="text-align:center"><span data-token="TITLE"></span></p>
                <p data-style="cover_subtitle" style="text-align:center">By <span data-token="AUTHOR_FULL_NAME"></span></p>
                """);

        Chapter chapter = chapterDao.create(book.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(),
                "<p>One two three four five.</p>", 5);

        ExportService.ExportMeta meta = service.exportBook(book.getId());

        List<String> paragraphs = paragraphTexts(meta.bytes());
        assertTrue(paragraphs.stream().anyMatch(p -> p.equals(book.getTitle())));
        assertTrue(paragraphs.stream().anyMatch(p -> p.equals("By Jane Doe")));
    }

    @Test
    void exportBookThrowsForUnknownId() {
        assertThrows(IllegalArgumentException.class, () -> service.exportBook(UUID.randomUUID()));
    }

    // -------------------------------------------------------------------------
    // Page layout
    // -------------------------------------------------------------------------

    @Test
    void exportAppliesConfiguredCustomPageSizeToMainContentSection() throws Exception {
        pageLayoutDao.upsertBook(book.getId(), PageLayout.builder()
                .pageLayoutEnabled(true)
                .pageSizePreset("CUSTOM")
                .pageWidthIn(6.0)
                .pageHeightIn(9.0)
                .pageMarginTopIn(0.75)
                .pageMarginBottomIn(0.75)
                .pageMarginInnerIn(0.5)
                .pageMarginOuterIn(0.5)
                .build());

        Chapter chapter = chapterDao.create(book.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Content.</p>", 1);

        ExportService.ExportMeta meta = service.exportBook(book.getId());

        try (XWPFDocument doc = new XWPFDocument(new ByteArrayInputStream(meta.bytes()))) {
            CTSectPr mainSectPr = doc.getDocument().getBody().getSectPr();
            assertEquals(BigInteger.valueOf(Math.round(6.0 * 1440)), mainSectPr.getPgSz().getW());
            assertEquals(BigInteger.valueOf(Math.round(9.0 * 1440)), mainSectPr.getPgSz().getH());
            assertEquals(BigInteger.valueOf(Math.round(0.75 * 1440)), mainSectPr.getPgMar().getTop());
            assertEquals(BigInteger.valueOf(Math.round(0.5 * 1440)), mainSectPr.getPgMar().getLeft());
        }
    }

    @Test
    void exportAppliesConfiguredCustomPageSizeToCoverSectionToo() throws Exception {
        pageLayoutDao.upsertBook(book.getId(), PageLayout.builder()
                .pageLayoutEnabled(true)
                .pageSizePreset("CUSTOM")
                .pageWidthIn(6.0)
                .pageHeightIn(9.0)
                .pageMarginTopIn(0.75)
                .pageMarginBottomIn(0.75)
                .pageMarginInnerIn(0.5)
                .pageMarginOuterIn(0.5)
                .build());

        bookDao.setCoverImage(book.getId(), tinyPng(), "image/png");
        Chapter chapter = chapterDao.create(book.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Content.</p>", 1);

        ExportService.ExportMeta meta = service.exportBook(book.getId());

        try (XWPFDocument doc = new XWPFDocument(new ByteArrayInputStream(meta.bytes()))) {
            // The cover section is the embedded sectPr on the first paragraph
            // that carries one (the section-break paragraph inserted right
            // after the cover image/title page). It must match the same
            // custom size as the document-level (main content) section.
            CTSectPr coverSectPr = doc.getParagraphs().stream()
                    .map(p -> p.getCTP().getPPr())
                    .filter(pPr -> pPr != null && pPr.isSetSectPr())
                    .map(pPr -> pPr.getSectPr())
                    .findFirst()
                    .orElseThrow(() -> new AssertionError("Expected an embedded cover-section sectPr"));

            assertEquals(BigInteger.valueOf(Math.round(6.0 * 1440)), coverSectPr.getPgSz().getW());
            assertEquals(BigInteger.valueOf(Math.round(9.0 * 1440)), coverSectPr.getPgSz().getH());
            assertEquals(BigInteger.valueOf(Math.round(0.75 * 1440)), coverSectPr.getPgMar().getTop());
            assertEquals(BigInteger.valueOf(Math.round(0.5 * 1440)), coverSectPr.getPgMar().getLeft());
        }
    }

    @Test
    void exportUsesLetterSizeWhenPageLayoutDisabled() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Content.</p>", 1);

        ExportService.ExportMeta meta = service.exportBook(book.getId());

        try (XWPFDocument doc = new XWPFDocument(new ByteArrayInputStream(meta.bytes()))) {
            CTSectPr mainSectPr = doc.getDocument().getBody().getSectPr();
            assertEquals(BigInteger.valueOf(Math.round(8.5 * 1440)), mainSectPr.getPgSz().getW());
            assertEquals(BigInteger.valueOf(Math.round(11.0 * 1440)), mainSectPr.getPgSz().getH());
        }
    }

    // -------------------------------------------------------------------------
    // Filenames
    // -------------------------------------------------------------------------

    @Test
    void filenameSanitizesIllegalCharactersFromBookTitle() throws Exception {
        Book messyBook = bookDao.create(project.getId(), "Book: The \"Sequel\"?", null, null, null);
        Chapter chapter = chapterDao.create(messyBook.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Content.</p>", 1);

        ExportService.ExportMeta meta = service.exportBook(messyBook.getId());

        assertFalse(meta.filename().contains(":"));
        assertFalse(meta.filename().contains("\""));
        assertFalse(meta.filename().contains("?"));
        assertTrue(meta.filename().endsWith(".docx"));
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private List<String> paragraphTexts(byte[] docxBytes) throws Exception {
        try (XWPFDocument doc = new XWPFDocument(new ByteArrayInputStream(docxBytes))) {
            return doc.getParagraphs().stream()
                    .map(XWPFParagraph::getText)
                    .toList();
        }
    }

    private int indexOfContaining(List<String> paragraphs, String needle) {
        for (int i = 0; i < paragraphs.size(); i++) {
            if (paragraphs.get(i).contains(needle)) {
                return i;
            }
        }
        return -1;
    }

    /** A minimal valid 1x1 PNG, generated via ImageIO so it round-trips through ImageIO.read(). */
    private byte[] tinyPng() throws Exception {
        BufferedImage image = new BufferedImage(1, 1, BufferedImage.TYPE_INT_RGB);
        image.setRGB(0, 0, 0xFFFFFF);
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            ImageIO.write(image, "png", out);
            return out.toByteArray();
        }
    }
}
