package com.richardsand.novelkms.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.util.UUID;

import javax.imageio.ImageIO;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.richardsand.novelkms.NovelKmsTestBase;
import com.richardsand.novelkms.dao.PageLayoutDao;
import com.richardsand.novelkms.dao.PartDao;
import com.richardsand.novelkms.dao.TemplateDao;
import com.richardsand.novelkms.model.PageLayout;
import com.richardsand.novelkms.model.Part;
import com.richardsand.novelkms.model.Project;
import com.richardsand.novelkms.model.book.Book;
import com.richardsand.novelkms.model.chapter.Chapter;

/**
 * Covers {@link PdfExportService} across all four export scopes: content
 * fidelity (headings, scene breaks, cover-template tokens), page-layout
 * dimension mapping — including the cover/title pages, which (unlike DOCX)
 * correctly pick up a custom page size — and running-header suppression on
 * cover pages.
 *
 * <p>
 * Tests re-open the generated bytes with PDFBox and inspect extracted text
 * and page geometry, the same way a human reviewer would open the file in a
 * PDF viewer.
 */
class PdfExportServiceTest extends NovelKmsTestBase {

    private PartDao          partDao;
    private PageLayoutDao    pageLayoutDao;
    private PdfExportService service;

    private Project project;
    private Book    book;

    @BeforeEach
    void setUp() throws Exception {
        truncateAll();
        partDao = new PartDao(ds);
        pageLayoutDao = new PageLayoutDao(ds);
        service = new PdfExportService(bookDao, partDao, chapterDao, sceneDao, projectDao, templateDao, pageLayoutDao);

        project = projectDao.create("Test Project", null);
        book = bookDao.create(project.getId(), "The Long Way Home", null, "Long Way", null);
    }

    // -------------------------------------------------------------------------
    // Scene scope
    // -------------------------------------------------------------------------

    @Test
    void exportSceneReturnsRawContentWithNoHeading() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "Chapter One", null, null);
        var     scene   = sceneDao.create(chapter.getId(), "Opening", null);
        sceneDao.saveContent(scene.getId(), "<p>The rain had not stopped for three days.</p>", 8);

        PdfExportService.ExportMeta meta = service.exportScene(scene.getId());

        assertTrue(meta.filename().endsWith(".pdf"));
        String text = fullText(meta.bytes());
        assertTrue(text.contains("The rain had not stopped for three days."));
        assertFalse(text.contains("Chapter One"));
    }

    @Test
    void exportSceneThrowsForUnknownId() {
        assertThrows(IllegalArgumentException.class, () -> service.exportScene(UUID.randomUUID()));
    }

    // -------------------------------------------------------------------------
    // Chapter scope
    // -------------------------------------------------------------------------

    @Test
    void exportChapterIncludesChapterTitleHeading() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "The Beginning", "A Prologue", null);
        var     scene   = sceneDao.create(chapter.getId(), "Scene 1", null);
        sceneDao.saveContent(scene.getId(), "<p>It started, as these things do, with a letter.</p>", 9);

        PdfExportService.ExportMeta meta = service.exportChapter(chapter.getId());

        String text = fullText(meta.bytes());
        assertTrue(text.contains("The Beginning"));
        assertTrue(text.contains("A Prologue"));
        assertTrue(text.contains("It started, as these things do"));
    }

    @Test
    void exportChapterRendersSceneBreakBetweenMultipleScenes() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "Two Scenes", null, null);
        var     sceneA  = sceneDao.create(chapter.getId(), "A", null);
        sceneDao.saveContent(sceneA.getId(), "<p>First scene content.</p>", 3);
        var sceneB = sceneDao.create(chapter.getId(), "B", null);
        sceneDao.saveContent(sceneB.getId(), "<p>Second scene content.</p>", 3);

        PdfExportService.ExportMeta meta = service.exportChapter(chapter.getId());

        String text = fullText(meta.bytes());
        assertTrue(text.contains("* * *"));
        int firstIdx  = text.indexOf("First scene content");
        int breakIdx  = text.indexOf("* * *");
        int secondIdx = text.indexOf("Second scene content");
        assertTrue(firstIdx >= 0 && breakIdx > firstIdx && secondIdx > breakIdx);
    }

    @Test
    void exportChapterConvertsInlineHorizontalRuleToSceneBreak() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "One Scene, Inline Break", null, null);
        var     scene   = sceneDao.create(chapter.getId(), "Only", null);
        sceneDao.saveContent(scene.getId(),
                "<p>Before the break.</p><hr><p>After the break.</p>", 6);

        PdfExportService.ExportMeta meta = service.exportChapter(chapter.getId());

        String text = fullText(meta.bytes());
        assertTrue(text.contains("* * *"));
        int beforeIdx = text.indexOf("Before the break");
        int breakIdx  = text.indexOf("* * *");
        int afterIdx  = text.indexOf("After the break");
        assertTrue(beforeIdx < breakIdx && breakIdx < afterIdx);
    }

    @Test
    void exportChapterThrowsForUnknownId() {
        assertThrows(IllegalArgumentException.class, () -> service.exportChapter(UUID.randomUUID()));
    }

    // -------------------------------------------------------------------------
    // Part scope
    // -------------------------------------------------------------------------

    @Test
    void exportPartIncludesPartHeadingAndAllItsChapters() throws Exception {
        Part    part = partDao.create(book.getId(), "Origins", "How it all began", null);
        Chapter ch1  = chapterDao.create(book.getId(), part.getId(), "First Light", null, null);
        sceneDao.saveContent(sceneDao.create(ch1.getId(), "s", null).getId(), "<p>Dawn broke.</p>", 2);
        Chapter ch2 = chapterDao.create(book.getId(), part.getId(), "Second Light", null, null);
        sceneDao.saveContent(sceneDao.create(ch2.getId(), "s", null).getId(), "<p>Noon came.</p>", 2);

        PdfExportService.ExportMeta meta = service.exportPart(part.getId());

        String text = fullText(meta.bytes());
        assertTrue(text.contains("Origins"));
        assertTrue(text.contains("How it all began"));
        assertTrue(text.contains("First Light"));
        assertTrue(text.contains("Second Light"));
    }

    @Test
    void exportPartFallsBackToRomanNumeralWhenTitleBlank() throws Exception {
        Part part = partDao.create(book.getId(), "", null, null);

        PdfExportService.ExportMeta meta = service.exportPart(part.getId());

        String text = fullText(meta.bytes());
        assertTrue(text.contains("Part "));
    }

    // -------------------------------------------------------------------------
    // Book scope
    // -------------------------------------------------------------------------

    @Test
    void exportBookOrdersPartChaptersBeforeDirectChapters() throws Exception {
        Part    part   = partDao.create(book.getId(), "Part One", null, null);
        Chapter inPart = chapterDao.create(book.getId(), part.getId(), "In The Part", null, null);
        sceneDao.saveContent(sceneDao.create(inPart.getId(), "s", null).getId(), "<p>Inside the part.</p>", 3);
        Chapter direct = chapterDao.create(book.getId(), null, "Direct Chapter", null, null);
        sceneDao.saveContent(sceneDao.create(direct.getId(), "s", null).getId(), "<p>Outside any part.</p>", 3);

        PdfExportService.ExportMeta meta = service.exportBook(book.getId());

        String text      = fullText(meta.bytes());
        int    partIdx   = text.indexOf("Part One");
        int    inPartIdx = text.indexOf("In The Part");
        int    directIdx = text.indexOf("Direct Chapter");
        assertTrue(partIdx >= 0 && partIdx < inPartIdx);
        assertTrue(inPartIdx < directIdx);
    }

    @Test
    void exportBookWithCoverImageRendersSuccessfully() throws Exception {
        bookDao.setCoverImage(book.getId(), tinyPng(), "image/png");
        Chapter chapter = chapterDao.create(book.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Content.</p>", 1);

        PdfExportService.ExportMeta meta = service.exportBook(book.getId());

        try (PDDocument doc = Loader.loadPDF(meta.bytes())) {
            assertTrue(doc.getNumberOfPages() >= 2);
        }
    }

    @Test
    void exportBookResolvesCoverTemplateTokens() throws Exception {
        Project updatedProject = Project.builder()
                .id(project.getId())
                .title(project.getTitle())
                .authorFirstName("Jane")
                .authorLastName("Doe")
                .copyright("\u00a9 2026 Jane Doe")
                .build();
        projectDao.update(updatedProject);

        templateDao.upsertBookOverride(book.getId(), TemplateDao.TYPE_COVER, """
                <p data-style="cover_title" style="text-align:center"><span data-token="TITLE"></span></p>
                <p data-style="cover_subtitle" style="text-align:center">By <span data-token="AUTHOR_FULL_NAME"></span></p>
                """);

        Chapter chapter = chapterDao.create(book.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(),
                "<p>One two three four five.</p>", 5);

        PdfExportService.ExportMeta meta = service.exportBook(book.getId());

        String text = fullText(meta.bytes());
        assertTrue(text.contains(book.getTitle()));
        assertTrue(text.contains("By Jane Doe"));
    }

    @Test
    void exportBookThrowsForUnknownId() {
        assertThrows(IllegalArgumentException.class, () -> service.exportBook(UUID.randomUUID()));
    }

    // -------------------------------------------------------------------------
    // Page layout
    // -------------------------------------------------------------------------

    @Test
    void exportAppliesConfiguredCustomPageSizeToCoverPagesToo() throws Exception {
        pageLayoutDao.upsertBook(book.getId(), PageLayout.builder()
                .pageLayoutEnabled(true)
                .pageSizePreset("CUSTOM")
                .pageWidthIn(6.0)
                .pageHeightIn(9.0)
                .pageMarginTopIn(0.75)
                .pageMarginBottomIn(0.75)
                .pageMarginInnerIn(0.5)
                .pageMarginOuterIn(0.5)
                .build());

        bookDao.setCoverImage(book.getId(), tinyPng(), "image/png");
        Chapter chapter = chapterDao.create(book.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Content.</p>", 1);

        PdfExportService.ExportMeta meta = service.exportBook(book.getId());

        try (PDDocument doc = Loader.loadPDF(meta.bytes())) {
            double expectedWidthPt  = 6.0 * 72.0;
            double expectedHeightPt = 9.0 * 72.0;

            PDRectangle coverPage = doc.getPage(0).getMediaBox();
            assertEquals(expectedWidthPt, coverPage.getWidth(), 1.0);
            assertEquals(expectedHeightPt, coverPage.getHeight(), 1.0);

            PDRectangle lastPage = doc.getPage(doc.getNumberOfPages() - 1).getMediaBox();
            assertEquals(expectedWidthPt, lastPage.getWidth(), 1.0);
            assertEquals(expectedHeightPt, lastPage.getHeight(), 1.0);
        }
    }

    @Test
    void exportUsesLetterSizeWhenPageLayoutDisabled() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Content.</p>", 1);

        PdfExportService.ExportMeta meta = service.exportBook(book.getId());

        try (PDDocument doc = Loader.loadPDF(meta.bytes())) {
            PDRectangle page = doc.getPage(0).getMediaBox();
            assertEquals(8.5 * 72.0, page.getWidth(), 1.0);
            assertEquals(11.0 * 72.0, page.getHeight(), 1.0);
        }
    }

    // -------------------------------------------------------------------------
    // Running header
    // -------------------------------------------------------------------------

    @Test
    void runningHeaderAppearsOnBodyPagesButNotCoverPages() throws Exception {
        Project updatedProject = Project.builder()
                .id(project.getId())
                .title(project.getTitle())
                .authorLastName("Sand")
                .build();
        projectDao.update(updatedProject);

        bookDao.setCoverImage(book.getId(), tinyPng(), "image/png");
        Chapter chapter = chapterDao.create(book.getId(), null, "Ch One", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Body content.</p>", 2);

        PdfExportService.ExportMeta meta = service.exportBook(book.getId());

        // The running header format is "LastName / ShortTitle / {page}". Check
        // for that distinctive slash-separated fingerprint rather than a bare
        // "Sand" substring — the default SYSTEM cover template's own "By
        // {AUTHOR_FULL_NAME}" line legitimately renders "Sand" as body content
        // on the title page, which would otherwise collide with this check.
        String headerFingerprint = "Sand / " + book.getShortTitle() + " /";

        try (PDDocument doc = Loader.loadPDF(meta.bytes())) {
            // Page 1 = cover image, page 2 = title page. Neither should carry
            // the running header (mirrors DOCX's section-break exclusion).
            assertFalse(pageText(doc, 1).contains(headerFingerprint));
            assertFalse(pageText(doc, 2).contains(headerFingerprint));

            // The last page is manuscript body content and must carry it.
            String lastPageText = pageText(doc, doc.getNumberOfPages());
            assertTrue(lastPageText.contains(headerFingerprint));
        }
    }

    // -------------------------------------------------------------------------
    // HTML escaping
    // -------------------------------------------------------------------------

    @Test
    void chapterTitleWithSpecialCharactersIsEscapedCorrectly() throws Exception {
        Chapter chapter = chapterDao.create(book.getId(), null, "Tom & Jerry's <Big> Day", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Content.</p>", 1);

        PdfExportService.ExportMeta meta = service.exportChapter(chapter.getId());

        String text = fullText(meta.bytes());
        assertTrue(text.contains("Tom & Jerry's <Big> Day"));
    }

    // -------------------------------------------------------------------------
    // Filenames
    // -------------------------------------------------------------------------

    @Test
    void filenameSanitizesIllegalCharactersFromBookTitle() throws Exception {
        Book    messyBook = bookDao.create(project.getId(), "Book: The \"Sequel\"?", null, null, null);
        Chapter chapter   = chapterDao.create(messyBook.getId(), null, "Ch", null, null);
        sceneDao.saveContent(sceneDao.create(chapter.getId(), "s", null).getId(), "<p>Content.</p>", 1);

        PdfExportService.ExportMeta meta = service.exportBook(messyBook.getId());

        assertFalse(meta.filename().contains(":"));
        assertFalse(meta.filename().contains("\""));
        assertFalse(meta.filename().contains("?"));
        assertTrue(meta.filename().endsWith(".pdf"));
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private String fullText(byte[] pdfBytes) throws Exception {
        try (PDDocument doc = Loader.loadPDF(pdfBytes)) {
            return new PDFTextStripper().getText(doc);
        }
    }

    /** Extracts the text of a single 1-based page index. */
    private String pageText(PDDocument doc, int pageNumberOneBased) throws Exception {
        PDFTextStripper stripper = new PDFTextStripper();
        stripper.setStartPage(pageNumberOneBased);
        stripper.setEndPage(pageNumberOneBased);
        return stripper.getText(doc);
    }

    /** A minimal valid 1x1 PNG, generated via ImageIO so it round-trips through decoding. */
    private byte[] tinyPng() throws Exception {
        BufferedImage image = new BufferedImage(1, 1, BufferedImage.TYPE_INT_RGB);
        image.setRGB(0, 0, 0xFFFFFF);
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            ImageIO.write(image, "png", out);
            return out.toByteArray();
        }
    }
}
